name: linting, testing, building
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  pipeline:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Check out repository code
      - uses: actions/checkout@v3
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        run: npm run test:ui:ci

